apiVersion: v1
kind: Secret
metadata:
  name: {{ include "binflow.fullname" . }}-secret
  labels:
    {{- include "binflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  BINFLOW_ADMIN_PASSWORD: {{ .Values.admin.password | quote }}